export interface ServiceData {
  title: string;
  description: string;
  story: string;
  whoFor: string;
  included: string[];
  preparation: string[];
  aftercare: string;
  price: string;
  isAddOn?: boolean;
  image?: string;
}

export const servicesData: Record<string, ServiceData> = {
  'balinese-massage': {
    title: 'Balinese Massage',
    description: 'A traditional Indonesian massage combining acupressure, stretching, and aromatherapy. Promotes deep relaxation and energy flow.',
    story: 'Originating from the island of Bali, this ancient healing tradition combines techniques from India, China, and Southeast Asia. Balinese massage uses a combination of gentle stretches, acupressure, reflexology, and aromatherapy to balance the body\'s energy and promote deep relaxation.',
    whoFor: 'Perfect for those seeking a holistic approach to relaxation. Ideal for stress relief, muscle tension, and overall wellness. Suitable for all fitness levels.',
    included: [
      'Traditional Balinese massage techniques',
      'Aromatherapy with essential oils',
      'Acupressure point stimulation',
      'Gentle stretching movements',
      'Full-body treatment',
      'Aftercare consultation',
    ],
    preparation: [
      'A quiet, comfortable space (bedroom or living room)',
      'Clean linens or towels for the massage surface',
      'Dim lighting (candles or soft lamps)',
      'Comfortable room temperature',
      'Time to rest afterward (1-2 hours recommended)',
    ],
    aftercare: 'Rest for at least 30 minutes. Hydrate with warm water or herbal tea. Avoid heavy meals immediately after. The relaxing effects often last for several hours.',
    price: 'AED 320',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop&q=80',
  },
  'thai-massage': {
    title: 'Thai Massage',
    description: 'Ancient Thai healing art combining acupressure, yoga-like stretching, and energy work. Performed on a mat with the client fully clothed.',
    story: 'Thai massage, also known as "lazy yoga," has been practiced for over 2,500 years. This unique form of bodywork combines acupressure, Indian Ayurvedic principles, and assisted yoga postures. Unlike traditional massage, Thai massage is performed on a mat with the client fully clothed, making it accessible and comfortable.',
    whoFor: 'Ideal for those who prefer to remain clothed during treatment. Perfect for improving flexibility, reducing muscle tension, and enhancing energy flow. Great for athletes and active individuals.',
    included: [
      'Traditional Thai massage techniques',
      'Yoga-like stretching',
      'Acupressure along energy lines',
      'Joint mobilization',
      'Energy balancing',
      'Full-body treatment',
    ],
    preparation: [
      'Wear comfortable, loose-fitting clothing',
      'A space large enough for a floor mat',
      'Clean mat or floor surface',
      'Comfortable room temperature',
      'Time to rest afterward',
    ],
    aftercare: 'Drink plenty of water. Avoid strenuous activity for a few hours. You may feel more flexible and energized. Some mild soreness is normal and should subside within 24 hours.',
    price: 'AED 380',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop&q=80',
  },
  'swedish-relaxing-massage': {
    title: 'Swedish Relaxing Massage',
    description: 'Classic European massage using long, flowing strokes, kneading, and circular movements. Perfect for stress relief and overall relaxation.',
    story: 'Swedish massage, developed in the 19th century by Per Henrik Ling, is the foundation of Western massage therapy. This gentle, flowing technique uses long strokes, kneading, and circular movements to promote relaxation, improve circulation, and reduce muscle tension.',
    whoFor: 'Perfect for first-time massage clients or anyone seeking gentle, relaxing touch. Ideal for stress relief, general wellness, and improving circulation. Suitable for all ages.',
    included: [
      'Classic Swedish massage techniques',
      'Long, flowing strokes',
      'Kneading and circular movements',
      'Light to medium pressure',
      'Full-body treatment',
      'Relaxing aromatherapy (optional)',
    ],
    preparation: [
      'A quiet, comfortable space',
      'Massage table or comfortable bed',
      'Clean linens',
      'Soft lighting',
      'Comfortable room temperature',
      'Time to rest afterward',
    ],
    aftercare: 'Rest for 30-60 minutes. Hydrate well. Avoid heavy meals immediately after. You should feel relaxed and rejuvenated. The calming effects can last for several hours.',
    price: 'AED 320',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop&q=80',
  },
  'deep-tissue-massage': {
    title: 'Deep Tissue Massage',
    description: 'Intensive massage targeting deeper layers of muscle and connective tissue. Ideal for chronic pain, tension, and injury recovery.',
    story: 'Deep tissue massage uses slow, deliberate strokes with firm pressure to reach deeper layers of muscle and fascia. This therapeutic technique is designed to break down adhesions and chronic tension patterns, providing relief from persistent pain and stiffness.',
    whoFor: 'Ideal for those with chronic pain, muscle tension, or injury recovery needs. Perfect for athletes, desk workers, and anyone with persistent muscle issues. Not recommended for those who prefer gentle touch.',
    included: [
      'Deep tissue techniques',
      'Targeted pressure application',
      'Myofascial release',
      'Trigger point therapy',
      'Focus on problem areas',
      'Post-treatment guidance',
    ],
    preparation: [
      'A quiet, comfortable space',
      'Firm massage surface',
      'Clean linens',
      'Comfortable room temperature',
      'Time to rest afterward (2-3 hours recommended)',
      'Communicate any areas of concern beforehand',
    ],
    aftercare: 'Rest for at least 2 hours. Apply ice to any tender areas if needed. Hydrate well. Some soreness is normal and should subside within 24-48 hours. Avoid strenuous activity for 24 hours.',
    price: 'AED 400',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop&q=80',
  },
  'couples-massage': {
    title: 'Couples Massage',
    description: 'Share a relaxing experience with your partner. Two therapists work simultaneously in the same space, creating a harmonious wellness journey.',
    story: 'Couples massage allows you and your partner to experience relaxation together in the same room. Two skilled therapists work in perfect harmony, creating a synchronized experience that enhances connection and shared relaxation.',
    whoFor: 'Perfect for couples, friends, or family members who want to share a wellness experience. Ideal for anniversaries, special occasions, or simply spending quality time together.',
    included: [
      'Two therapists working simultaneously',
      'Synchronized massage experience',
      'Choice of massage styles for each person',
      'Shared relaxation space',
      'Full-body treatment for both',
      'Aftercare consultation',
    ],
    preparation: [
      'A larger space to accommodate two massage tables',
      'Two sets of clean linens',
      'Comfortable room temperature',
      'Soft, ambient lighting',
      'Time to rest together afterward',
      'Discuss preferences with both therapists',
    ],
    aftercare: 'Take time to rest together. Hydrate well. Avoid scheduling other activities immediately after. Enjoy the shared sense of relaxation and connection.',
    price: 'AED 640',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
  'hot-stone-massage': {
    title: 'Hot Stone Massage',
    description: 'Smooth, heated stones are placed on key points and used to massage the body. Deeply relaxing and helps release muscle tension.',
    story: 'Hot stone massage uses smooth, heated basalt stones to provide deep, penetrating heat to muscles. This ancient technique combines the therapeutic benefits of heat with traditional massage, creating a uniquely relaxing and effective treatment.',
    whoFor: 'Perfect for those who love heat therapy and deep relaxation. Ideal for chronic muscle tension, stress relief, and improving circulation. Great for cold weather or when feeling chilled.',
    included: [
      'Heated basalt stones',
      'Stone placement on key points',
      'Stone massage techniques',
      'Full-body treatment',
      'Aromatherapy (optional)',
      'Aftercare guidance',
    ],
    preparation: [
      'A quiet, comfortable space',
      'Massage table or comfortable surface',
      'Clean linens',
      'Comfortable room temperature',
      'Time to rest afterward',
      'Communicate any heat sensitivity',
    ],
    aftercare: 'Rest for at least an hour. Hydrate well with water. The heat effects continue for several hours. Avoid hot showers or baths immediately after.',
    price: 'AED 400',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
  'sport-massage': {
    title: 'Sport Massage',
    description: 'Specialized massage for athletes focusing on muscle recovery, injury prevention, and performance enhancement. Combines deep tissue and stretching techniques.',
    story: 'Sports massage is specifically designed for athletes and active individuals. This technique combines deep tissue work, stretching, and movement to enhance performance, prevent injury, and speed recovery. Whether you\'re training for competition or maintaining an active lifestyle, sports massage supports your body\'s needs.',
    whoFor: 'Ideal for athletes, fitness enthusiasts, runners, and anyone with an active lifestyle. Perfect for pre-event preparation, post-event recovery, or regular maintenance. Suitable for all sports and activity levels.',
    included: [
      'Sports-specific techniques',
      'Deep tissue work',
      'Active and passive stretching',
      'Targeted muscle release',
      'Injury prevention focus',
      'Performance enhancement strategies',
    ],
    preparation: [
      'A quiet, comfortable space',
      'Firm massage surface',
      'Clean linens',
      'Comfortable room temperature',
      'Time to rest afterward',
      'Share your training schedule and goals',
    ],
    aftercare: 'Hydrate well with water and electrolytes. Rest for 1-2 hours. Light stretching is beneficial. Avoid intense training for 24 hours. The recovery benefits continue for several days.',
    price: 'AED 680',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop',
  },
  'aromatherapy-massage': {
    title: 'Aromatherapy Massage',
    description: 'Swedish massage enhanced with essential oils chosen for their therapeutic properties. Promotes relaxation, mood enhancement, and overall well-being.',
    story: 'Aromatherapy massage combines the therapeutic benefits of touch with the healing power of essential oils. Each oil is carefully selected for its unique properties—some promote relaxation, others energize, and many support emotional balance. The combination of massage and aromatherapy creates a deeply holistic healing experience.',
    whoFor: 'Perfect for those seeking emotional and physical wellness. Ideal for stress relief, mood enhancement, and overall relaxation. Great for those who enjoy scents and aromatherapy.',
    included: [
      'Swedish massage techniques',
      'Custom essential oil blend',
      'Aromatherapy consultation',
      'Full-body treatment',
      'Mood and wellness support',
      'Aftercare with oil recommendations',
    ],
    preparation: [
      'A quiet, comfortable space',
      'Massage table or comfortable surface',
      'Clean linens',
      'Soft lighting',
      'Comfortable room temperature',
      'Time to rest afterward',
      'Share any scent preferences or sensitivities',
    ],
    aftercare: 'Rest for at least an hour. The essential oils continue to work through your system. Hydrate well. Avoid washing immediately to allow oils to absorb. The calming effects can last for hours.',
    price: 'AED 400',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
  'four-hand-massage': {
    title: 'Four Hand Massage',
    description: 'Two therapists work in perfect synchronization, creating a unique and deeply relaxing experience. Double the touch, double the relaxation.',
    story: 'Four-hand massage, also known as synchronized massage, is a luxurious experience where two therapists work together in perfect harmony. The synchronized movements create a unique rhythm and flow that enhances relaxation and provides comprehensive coverage of the entire body simultaneously.',
    whoFor: 'Perfect for those seeking an extra-special, luxurious experience. Ideal for special occasions, deep relaxation, or when you want the ultimate massage experience. Great for those who love being fully enveloped in therapeutic touch.',
    included: [
      'Two synchronized therapists',
      'Perfectly coordinated movements',
      'Comprehensive full-body coverage',
      'Enhanced relaxation experience',
      'Luxury treatment',
      'Aftercare consultation',
    ],
    preparation: [
      'A larger space for two therapists',
      'Massage table or comfortable surface',
      'Clean linens',
      'Soft, ambient lighting',
      'Comfortable room temperature',
      'Time to fully rest afterward',
    ],
    aftercare: 'Rest for at least 2 hours. This is an intense relaxation experience—allow time for integration. Hydrate well. Avoid scheduling other activities. The deep relaxation effects can last for days.',
    price: 'AED 550',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
  'head-neck-shoulder-massage': {
    title: 'Head, Neck & Shoulder Massage',
    description: 'Focused massage targeting the upper body to relieve tension, headaches, and stress. Perfect for desk workers and those with neck and shoulder pain.',
    story: 'The head, neck, and shoulders are common areas of tension, especially for those who work at desks or experience stress. This focused treatment targets these specific areas with precision, providing relief from headaches, neck pain, and shoulder tension.',
    whoFor: 'Perfect for desk workers, those with computer-related tension, or anyone experiencing headaches, neck pain, or shoulder stiffness. Ideal for quick relief during lunch breaks or after work.',
    included: [
      'Focused upper body treatment',
      'Neck and shoulder release',
      'Scalp massage',
      'Headache relief techniques',
      'Targeted tension release',
      'Posture awareness guidance',
    ],
    preparation: [
      'A comfortable chair or massage table',
      'Clean linens',
      'Comfortable room temperature',
      'Quiet environment',
      'Time to rest afterward',
    ],
    aftercare: 'Rest for 30 minutes. Hydrate well. Avoid looking down at screens immediately after. Practice gentle neck stretches. The relief from tension can last for several hours.',
    price: 'AED 160',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop',
  },
  'facial-massage': {
    title: 'Facial Massage',
    description: 'Gentle, rejuvenating massage for the face and neck. Promotes circulation, reduces tension, and enhances skin health.',
    story: 'Facial massage is a gentle, therapeutic technique that promotes circulation, reduces facial tension, and enhances skin health. This add-on treatment complements any full-body massage, providing comprehensive relaxation and rejuvenation.',
    whoFor: 'Perfect as an add-on to any 60-minute massage. Ideal for those seeking facial rejuvenation, tension relief in the jaw and face, or enhanced skin health. Great for anyone who wants a complete wellness experience.',
    included: [
      'Gentle facial massage techniques',
      'Neck and jaw release',
      'Circulation enhancement',
      'Skin health support',
      'Tension relief',
      'Relaxing facial treatment',
    ],
    preparation: [
      'Available as add-on only',
      'Requires 60-minute base massage',
      'Clean face (makeup removed)',
      'Comfortable positioning',
    ],
    aftercare: 'Allow the natural oils to absorb. Avoid washing face immediately. The rejuvenating effects continue for several hours. Skin may appear more radiant.',
    price: 'AED 65',
    isAddOn: true,
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
  'foot-massage': {
    title: 'Foot Massage',
    description: 'Reflexology-based foot massage targeting pressure points connected to the entire body. Relieves tension and promotes overall wellness.',
    story: 'Foot massage, based on reflexology principles, works on the theory that different points on the feet correspond to different organs and systems in the body. This add-on treatment provides comprehensive wellness benefits while offering deep relaxation for tired, overworked feet.',
    whoFor: 'Perfect as an add-on to any 60-minute massage. Ideal for those who are on their feet all day, experience foot pain, or want to enhance their overall wellness through reflexology. Great for anyone seeking complete relaxation.',
    included: [
      'Reflexology techniques',
      'Pressure point stimulation',
      'Foot and ankle release',
      'Overall wellness support',
      'Tension relief',
      'Relaxing foot treatment',
    ],
    preparation: [
      'Available as add-on only',
      'Requires 60-minute base massage',
      'Clean feet',
      'Comfortable positioning',
    ],
    aftercare: 'Rest for 30 minutes. Hydrate well. The reflexology effects continue to work throughout the body. You may feel more balanced and relaxed overall.',
    price: 'AED 60',
    isAddOn: true,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop',
  },
  'scalp-massage': {
    title: 'Scalp Massage',
    description: 'Therapeutic scalp massage using gentle pressure and circular motions. Relieves tension, promotes relaxation, and improves scalp health.',
    story: 'Scalp massage is a deeply relaxing treatment that relieves tension in the head, neck, and shoulders. This add-on service uses gentle pressure and circular motions to promote circulation, reduce stress, and enhance overall relaxation.',
    whoFor: 'Perfect as an add-on to any 60-minute massage. Ideal for those experiencing headaches, scalp tension, or stress. Great for anyone who wants to enhance their relaxation experience with this soothing treatment.',
    included: [
      'Gentle scalp massage techniques',
      'Circular pressure movements',
      'Tension relief',
      'Circulation enhancement',
      'Relaxation promotion',
      'Scalp health support',
    ],
    preparation: [
      'Available as add-on only',
      'Requires 60-minute base massage',
      'Comfortable positioning',
      'Relaxed state',
    ],
    aftercare: 'Rest for 30 minutes. The relaxing effects continue. You may feel a sense of lightness and reduced tension in the head and neck area.',
    price: 'AED 60',
    isAddOn: true,
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800&h=600&fit=crop',
  },
};

